spring.application.name=Server
server.servlet.context-path=/api/v1
## DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5434/blogging-api-db
spring.datasource.username=admin-api
spring.datasource.password=admin-api
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=eW91ci12ZXJ5LXNlY3VyZS1zZWNyZXQta2V5LWhlcmU=
jwt.expiration=86400000
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=TRACE